MP_API_BASE = 'https://api.mercadopago.com'.freeze
MP_TEST_ACCESS_TOKEN = ENV["MP_TEST_ACCESS_TOKEN"]
MP_PRODUCTION_ACCESS_TOKEN = ENV["MP_PRODUCTION_ACCESS_TOKEN"]
MP_PUBLIC_KEY = ENV["MP_PUBLIC_KEY"]
MP_WEBHOOK_SECRET = ENV["MP_WEBHOOK_SECRET"]