MP_API_BASE = 'https://api.mercadopago.com'.freeze
MP_TEST_ACCESS_TOKEN = ENV.fetch("MP_TEST_ACCESS_TOKEN")
MP_PRODUCTION_ACCESS_TOKEN = ENV.fetch("MP_PRODUCTION_ACCESS_TOKEN")
MP_PUBLIC_KEY = ENV.fetch("MP_PUBLIC_KEY")
MP_WEBHOOK_SECRET = ENV.fetch("MP_WEBHOOK_SECRET")