load Rails.root.join('db/seeds/0-prepare.rb')
load Rails.root.join('db/seeds/1-companies.rb')
load Rails.root.join('db/seeds/2-users.rb')
load Rails.root.join('db/seeds/3-clients.rb')
load Rails.root.join('db/seeds/4-order_services.rb')
load Rails.root.join('db/seeds/5-assignments.rb')
load Rails.root.join('db/seeds/6-service_items.rb')